### ISSUE TITLE
"action detail" frame hidden by default?

### ISSUE THREAD

**Issue by Vdragon** [nsf/obkey#1]
I doesn't find any documentation though... is there any? ; )

**Comment by gitxpy** [comment]
this has been reported again e.g. http://www.lxle.net/forums/discussion/805/obkey-bug/p1

**Comment by gitxpy** [comment]
a quick wka could be  to add to PropertyTable.__init__ :
  self.widget.set_border_width(2)

not fully satisfactory for the size, but at least, the scrolledwindow is showing up
http://snag.gy/cvt3W.jpg
http://snag.gy/H8hcr.jpg

**Comment by nsf** [comment]
Guys I don't use obkey anymore, I moved to xfce4 like several years ago. I would say the best way to fix it would be to fork it. I guess I could accept pull requests. But doing so without testing is kind of meh.
